### ISSUE TITLE
Сверстать карточки для курсов на главной странице

### ISSUE THREAD

**Issue by SaadatKosumbaeva** [js13-esdp1/bilem#26]
### Мотивация
Сверстать карточки для курсов на главной странице

### Решение
Для курсов создать компонент на фронте.
Данный компонент должен быть общим как для платных, так и бесплатных курсов. Нужно добавить в ts файл курсов Input: title и менять его в зависимости от курсов (Платные курсы / Бесплатные курсы).
Список курсов должен отображаться по критериям: Популярные курсы / Новые курсы
Общий вид карточки взять из тз, предоставленного заказчиком (https://kiwi-breath-1f9.notion.site/0858727a8db1435e83e64f8cfa91e675?p=61c2b818fee74a298d0493c6db9fca8e).

### Критерий приемки
Общий вид блока с курсами должен отображаться согласно правилам, указанным в решении.

### Оценка
Планируемое время: 3ч
Фактическое время: 4ч

**Comment by IlyaGulchenko** [comment]
Возникли некоторые проблемы недопонимания, связанные с реализацией сортировки курсов по популярности/дате.
Так же небольшие проблемы были с версткой. В связи с чем фактическое время выполнения немного увеличилось.
