### ISSUE TITLE
Создание модерации для опубликование новых курсов.

### ISSUE THREAD

**Issue by IlyaGulchenko** [js13-esdp1/bilem#39]
### Мотивация

Создать модерацию при которой у администраторов сайта появляется возможность отсматривать новые добавленные курсы и публиковать.

### Решение

"Пользователи" видят только "опубликованные" курсы.
Также "Пользователи" видят собственные неопубликованные курсы с пометкой "неопубликовано".

"Администраторы" видят все курсы. У неопубликованных курсов должна отображаться пометка "неопубликовано".
 Для неопубликованных курсов отображается кнопка "Опубликовать".

При нажатии на кнопку "Опубликовать" производится изменение поля "is_published" выбранного курса с false на true.
А так же высвечивается сообщение, реализованное с помощью снэкбара: "Успешно опубликовано".

Действие "опубликовать" можно делать как методом POST на некий особый путь (/courses/:id/publish), так и методом PUT.

### Критерий приемки

Логинюсь в качестве обычного пользователя > создаю курс > вижу сообщение "Успешно. Ожидайте проверки модератора.", вижу созданный курс в перечне своих курсов с пометкой "неопубликованно" > перехожу на главную страницу и не нахожу созданного курса.

Логинюсь в качестве администратора > перехожу на главную страницу, вижу все курсы (опубликованные и нет) > проверяю неопубликованный курс, если все хорошо - кликаю на кнопку "Опубликовать" > вижу сообщение "Успешно опубликовано" > у курса пропадает пометка.

### Оценка
Планируемое время: 8 ч.
Фактическое время:

**Comment by tofustar1** [comment]
В ходе работы было решено добавить возможность удаления курса для администратора, а так же разбить компонент main-courses на два более мелких.
