### ISSUE TITLE
Прохождения курса, просмотр всех уроков и возможность оставить комментарий

### ISSUE THREAD

**Issue by AsylKydraliev** [js13-esdp1/bilem#56]
###Мотивация
Прохождения курса, т.е. просмотр всех уроков и возможность оставить комментарий 

###Решение
По клику на кнопку «Продолжить» на странице курса происходит редирект на страницу прохождения курса (т.е. его уроков). Для этой страницы необходимо создать новый компонент «lessons», который будет находится в router-outlet компонента «lessons-sidebar». Здесь в сайдбаре уроков по клику на название урока меняется контент урока (приходит информация запрашиваемого урока: название, описание, видео).
Осуществить добавление комментария к уроку. Для этого создать текстовое поле с кнопкой «Оставить комментарий». Также добавить поправки на бэкенд: в модель LessonsSchema добавить новое поле comments: [CommentsSchema]
const CommentsSchema = new Schema({
  user: {
    type: Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  text: String
});
В api добавить роут на создание комментария и роут с запросом всех комментариев, которые относятся к уроку. 
На странице после контента урока и поля добавления нового комментария вывести все комментарии этого урока.

###Критерий приемки
По нажатию на кнопку «Продолжить» происходит редирект на страницу прохождения курса. Изначально отображается информация первого урока в перовом модуле курса. По клику на название другого урока в сайдбаре выходит информация об этом уроке и его комментарии. Если ввести в поле комментария текст и нажать на кнопку «Оставить комментарий», то комментарий отобразится в списке всех комментариев (первым сверху).

###Сценарий на Gherkin
Допустим я нахожусь на странице просмотра курса
И кликаю на кнопку "Пройти курс"
И нажимаю на кнопку "Продолжить"
И я кликаю по названию урока "Lesson 1" 
И вижу информацию по этому уроку

###Оценка
Планируемое время: 6 часов
Фактическое время: 12 часов

**Comment by bakytai** [comment]
OverTime по причине - Возникли проблемы при выведении программы курса(именно переход сразу на страницу с контентом первого урока), также были проблемы при запросе комментариев с базы.
