### ISSUE TITLE
Поиск уроков автора на странице преподавания и сортировка списка курсов

### ISSUE THREAD

**Issue by AsylKydraliev** [js13-esdp1/bilem#63]
###Мотивация
1. Добавить поле для поиска уроков автора на странице преподавания
2. Сортировать список курсов, чтобы новый добавленный урок был первым в списке.

###Решение
1. Поиск уроков:
Чтобы сделать поиск по урокам автора, необходимо создать поле для ввода названия урока и сделать метод SearchLessons в том компоненте, где отображается список уроков. Можно взять массив уроков в state и использовать метод filter для поиска запрашиваемых уроков по их  названию. Поиск должен автоматически выводить все подходящие варианты уроков, для этого нужно взять значение, которое вводит пользователь и сравнить с названиями уроков в массиве уроков автора, можно использовать метод includes, все значения необходимо сделать в нижнем регистре, обратившись к строке (toLowerCase()), чтобы поиск не обращал внимания на буквы в верхнем регистре. 
3. Сортировка курсов:
Чтобы осуществить сортировку курсов автора, необходимо в API при запросе на курсы автора сортировать их по Id и отправлять клиенту уже в отсортированный массив с курсами автора, нежелательно делать это на клиенте, используя метод reverse() для массива курсов.

###Критерий приемки
1. Поиск уроков:
На странице преподавания должно быть поле для ввода названия урока с кнопкой Поиск, если я ввожу название урока все подходящие варианты должны отобразиться в этом же списке, то есть список должен меняться.
2. Сортировка курсов:
Списке курсов автора на странице преподавания должен быть отсортирован таким образом, чтобы новый созданный курс выходил первым списке.

###Сценарий на Gherkin
Функционал: Поиск уроков на странице Преподавания 
  Для того, чтобы пользователь мог быстро ориентироваться
  Как обычный пользователь
  Я должен иметь возможность искать уроки по их названию.

  @search_for_lessons
  Сценарий: Поиск уроков на странице Преподавания
    Допустим я нахожусь на странице Преподавания
    И я залогинен как пользователь "user@bilem.com"
    Если я ввожу в поле формы:
    | Поиск | JavaScript |
    Я должен увидеть уроки с подходящим названием

Планируемое время: 6 часов
Фактическое время: 8 часов

**Comment by bakytai** [comment]
Over Time по причине: были проблемы с интернетом в всокресенье
