### ISSUE TITLE
Реализация логики работы чекбокса "Запомнить меня" на страницах регистрации и логина

### ISSUE THREAD

**Issue by KamilyaMukhammedova** [js13-esdp1/bilem#85]
### Мотивация
На страницах регистрации и логина пользователя есть чекбокс "Запомнить меня". Необходимо добавить логику работы к нему. На этих же страницах и на странице восстановления пароля добавить небольшие изменения для улучшения работы этих страниц, так как при логине или регистрации через гугл сначала выходит ошибка, а затем происходит логин или регистрация. Это связано с тем, что иконки реализованы через инпут.

### Решение
Просмотреть и изучить информацию по логике работы чекбокса "Запомнить меня" и использовать подходящий подход на страницах регистрации и логина. На этих же страницах и на странице восстановления пароля изменить следующее:
- Логотип Bilem обернуть в ссылку, которая ведет на главную страницу.
- Иконки facebook и gmail: убрать инпуты, а вместо них добавить ссылки, а в них image

### Критерий приемки
На страницах регистрации и логина в случае нажатия на логотип перехожу на главную страницу с подборкой курсов. При нажатии на иконку гугл происходит успешный вход (без каких-либо предшествующих ошибок). После нажатия на чекбокс "Запомнить меня"в формах авторизации при последующих посещениях приложения моя сессия начинается автоматически.

Планируемое время: 9 часов
Фактическое время: 12ч

**Comment by bakytai** [comment]
OverTime: возникли проблемы с реализацией
